name: Build Ilm Minar APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.0'
        
    - name: Convert to Flutter
      run: |
        # Remove web files
        rm -rf src server index.html vite.config.js
        
        # Create Flutter project
        flutter create --org com.ilmminar --project-name ilm_minar_app .
        
    - name: Install Dependencies
      run: flutter pub get
      
    - name: Build APK
      run: flutter build apk --release
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: ilm-minar-app
        path: build/app/outputs/flutter-apk/app-release.apk
